/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Native_NativeHelloWorld */

#ifndef _Included_Native_NativeHelloWorld
#define _Included_Native_NativeHelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Native_NativeHelloWorld
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Native_NativeHelloWorld_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
